### PR TITLE
[JENKINS-51792] Change ModelParser to error only once when there are multiple steps blocks

### PR DESCRIPTION
**Pull request by kshultzCB**
* JENKINS issue(s):
    * [JENKINS-51792](https://issues.jenkins-ci.org/browse/JENKINS-51792)
* Description:
    * Given a malformed Pipeline, where there was more than one `steps` section inside of a `stage`, we were reporting a `Duplicate parallel branch name: "default"`. This was a bit confusing if the user's Pipeline had no branch named `default` in it at all. This change checks to make sure that the stage is empty before adding a `default` branch.
* Documentation changes:
    * No documentation changes should be necessary. This is just cleanup of some unnecessary error messages, which a user would only see if they had a mistake in their Pipeline anyway.
* Users/aliases to notify:
    * N/A

### CODE REVIEW

**Comment by kshultzCB** [comment]
[Build 2](https://ci.jenkins.io/job/Plugins/job/pipeline-model-definition-plugin/job/PR-303/2/) timed out on CI. I don't have the privileges on ci.jenkins.io to relaunch it.

image

**Comment by kshultzCB** [comment]
I'm doing the close/reopen dance to trigger another build. The  `windows-newer-core` branch timed out.

**Comment by kshultzCB** [comment]
Here's the reopen part of the dance.

**Comment by abayer** [comment]
@kshultzCB FYI, I just pushed a change to master to bump the job timeout to an hour from 90 minutes, since queue time can hose us.

**Comment by abayer** [comment]
...I also might get rid of `ExecuteConvertedTest` soon - it eats a lot of time but doesn't provide much real value, with some small tweaks to `ConvertRoundTripTest` to make sure it's covering every angle.

**Comment by abayer** [comment]
Re-running yet again to pick up the job timeout bump to 2 hours. sigh.

**Comment by abayer** [comment]
Test failure is bogus, I'm just merging.

**Pull request merged**
