### PR TITLE
Refresh sidebar icon

### PR DESCRIPTION
**Pull request by NotMyFault**
The change proposed makes use of the icon set found in core and many major plugins.

Before:

Screenshot 2022-09-07 at 00 07 47

After:
Screenshot 2023-05-16 at 09 31 23

### CODE REVIEW

**Comment by NotMyFault** [comment]
Ping @jenkinsci/pipeline-model-definition-plugin-developers mind taking a look? :)

**Comment by NotMyFault** [comment]
Hey @jenkinsci/pipeline-model-definition-plugin-developers, I rebased the PR to take the baseline bump into consideration and therefore the ionicon update.

**Comment by janfaracik** [comment]
Was about to look into doing this. Any chance of getting this in @jenkinsci/pipeline-model-definition-plugin-developers ?

**Comment by NotMyFault** [comment]
Hey @jglick,

do you mind taking a look at this PR?

Thanks in advance!

**Review by jglick — APPROVED** [review]

**Pull request merged**
