### PR TITLE
[JENKINS-26148] Using default implementation of StepExecution.stop

### PR DESCRIPTION
**Pull request by jglick**
Downstream of https://github.com/jenkinsci/workflow-step-api-plugin/pull/30.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
@reviewbybees done

**Comment by abayer** [comment]
@jglick Resolve the merge conflict and I'll merge.

**Comment by abayer** [comment]
Ignore my initial dumb backwards merge commit. Pushed the right merge to your branch, once it passes tests, I'll merge it.

**Comment by jglick** [comment]
@abayer passing.

**Pull request merged**
