### PR TITLE
Jenkins 49142

### PR DESCRIPTION
**Pull request by joseblas**
* JENKINS issue(s):
    * https://issues.jenkins-ci.org/browse/JENKINS-49142
* Description:
    * Be able to customize checkout as "options" in declarative pipeline
* Documentation changes:
    * https://github.com/jenkins-infra/jenkins.io/pull/1974
* Users/aliases to notify:
    * ...

### CODE REVIEW

**Comment by abayer** [comment]
Yeah, I'm still not a fan of this. I'd far prefer a specific-to-git `DeclarativeOption` that supported all git extensions without having to hardcode support for them one by one. Let's take this back to the drawing board.

**Comment by joseblas** [comment]
I'm going to close this and continue the conversation in Jira.

**Comment by zbynek** [comment]
@joseblas are you still interested in finishing this?

**Comment by bitwiseman** [comment]
https://github.com/jenkinsci/pipeline-model-definition-plugin/tree/issue/JENKINS-49142

**Pull request closed without merging**
