### PR TITLE
Require Jenkins 2.387.3 or newer

### PR DESCRIPTION
**Pull request by MarkEWaite**
## Require Jenkins 2.387.3 or newer (HTMLUnit 3 upgrade)

* Contents of pull request
    * #622 
    * #621 
    * Require Jenkins 2.387.3 or newer
    * Require workflow-cps 3691.v28b_14c465a_b_b_ for HTMLUnit 3
    * Test with git plugin 5.1.0 for HTMLUnit 3
    * Add git and httpcomponent test dependencies

* Supersedes pull requests
    * #616 

* JENKINS issue(s):
    * https://github.com/jenkinsci/jenkins-test-harness/releases/tag/2010.v1888f1a_cd45a_
    * https://github.com/jenkinsci/bom/pull/2158
    * https://github.com/jenkinsci/branch-api-plugin/pull/379
    * https://github.com/jenkinsci/workflow-cps-plugin/pull/723
    * https://github.com/jenkinsci/workflow-multibranch-plugin/pull/258
    * https://github.com/jenkinsci/workflow-scm-step-plugin/pull/126

* Description:
    * Upgrade to HTMLUnit 3 by making necessary upgrades of other components

* Documentation changes:
    * No documentation change required

* Users/aliases to notify:
    * @jglick
    * @timja

### CODE REVIEW

**Comment by jglick** [comment]
Possibly needs to be adapted to https://github.com/jenkinsci/jenkins-test-harness/pull/583; I will take a look when I get a moment.

**Comment by MarkEWaite** [comment]
> Possibly needs to be adapted to [jenkinsci/jenkins-test-harness#583](https://github.com/jenkinsci/jenkins-test-harness/pull/583); I will take a look when I get a moment.

Thanks very much.  I'm going to shift my focus to the `email-ext` test failure in https://github.com/jenkinsci/bom/pull/2158/checks?check_run_id=14078092522 .  It seems unrelated to the HTMLUnit 3 upgrade.

**Comment by MarkEWaite** [comment]
The email-ext failure is visible already when testing email-ext with Jenkins 2.409.  Seems to be dependent on Jenkins UI components that have been changed in recent releases.  I will submit a pull request to fix it and an exclusion to ignore that failure in the plugin BOM for now.

**Review by jglick — APPROVED** [review]

**Comment by MarkEWaite** [comment]
> (I am not marking this `developer` since I do not suppose this is needed for the `bom`, but let me know if you do need a release.)

I think that we need a release based on the [test failures](https://ci.jenkins.io/job/Tools/job/bom/job/master/1788/#showFailuresLink) in last night's attempt to release the BOM with git plugin 5.1.0, git client plugin 4.4.0 and the 4 Pipeline plugins that depend on git plugin.    The Pipeline build step plugin has been released with its necessary updates for HTMLUnit 3.  Once this plugin is released, I can try again for a BOM release.

**Comment by jglick** [comment]
https://github.com/jenkinsci/pipeline-model-definition-plugin/releases/tag/2.2141.v5402e818a_779

**Pull request merged**
