### PR TITLE
[JENKINS-58732] Remove docker-workflow dependency (refiled)

### PR DESCRIPTION
**Pull request by jglick**
Just the first commit from #391; whatever the purpose of the subsequent commits, they may have been made obsolete by changes in `master` since then.

Follows up #373 & #383.

Admins using `agent docker` / `agent dockerfile` should have updated to at least https://github.com/jenkinsci/docker-workflow-plugin/releases/tag/docker-workflow-1.22 first.

### CODE REVIEW

**Comment by chriskilding** [comment]
Provided it passes then this is fine by me. Glad to see there was a way to do this without the weird Hamcrest stuff.

**Comment by jglick** [comment]
http://stats.jenkins.io/pluginversions/docker-workflow.html suggests ~41% of installations have upgraded that, which seems low, but OTOH http://stats.jenkins.io/pluginversions/pipeline-model-definition.html suggests that only ~37% of installations have upgraded _this_ plugin, from which I conclude that most admins do not upgrade plugins in a timely fashion at all. The problem is only if someone upgrades `pipeline-model-definition` but _not_ `docker-workflow` (i.e., do not select all), and also happens to be using `agent docker` / `agent dockerfile`.

**Comment by bitwiseman** [comment]
@jglick
Okay, I'm going to wait one more version for this PR.

**Review by dwnusbaum — APPROVED** [review]

**Review by chriskilding — APPROVED** [review]

**Review by bitwiseman — APPROVED** [review]
Once we get a build that passes, I'll merge this.

**Comment by jglick** [comment]
And let me know when this is released, too: https://github.com/jenkinsci/docker-workflow-plugin/pull/230#issuecomment-713712865

**Comment by jglick** [comment]
https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/393/checks?check_run_id=1738226672 smell like flakes.

**Comment by bitwiseman** [comment]
@jglick 
Yes, we're definitely seeing flakes or infra issues.

**Comment by jglick** [comment]
Well most recent build was green finally.

**Pull request merged**
