### PR TITLE
[JENKINS-56379] Switch to f:hetero-list

### PR DESCRIPTION
**Pull request by jsoref**
* JENKINS issue(s):
    * [JENKINS-56379](https://issues.jenkins-ci.org/browse/JENKINS-56379).
* Description:
    * Reduce divergence from f:hetero-list (to enable f: widgets to change their stripes w/o this widget exploding)
* Documentation changes:
    * This is an internal change and shouldn't have any impact on the behavior today, but it will make it easier for my `<table>`->`<div>` changes to land w/o breaking this component/requiring a perfect cutover.
* Users/aliases to notify:
    * @abayer 

Note: this requires jenkinsci/jenkins#3922 to be merged and a bump of the pom.xml to require the version w/ that change. I'm not quite sure how to specify in the pom that it requires version X (normal) or version Y (LTS).

### CODE REVIEW

**Comment by abayer** [comment]
@jsoref - you need to edit the top-level POM and change the `jenkins.version` property. But I'm not sure how long it'll be 'til we move to a newer version of core for that to be an option, so I'm leaving this as WIP for now.

**Comment by jsoref** [comment]
@abayer: yeah, I mostly understand that, but how do I deal w/ LTS?

**Comment by jsoref** [comment]
Looks like the first available train would be September. I suspect this would work (minus the fact that September isn't here).

**Comment by bitwiseman** [comment]
@jsoref I've done a merge using the earliest LTS that contains this fix - 2.190.1.

**Comment by bitwiseman** [comment]
@jsoref  Why?

**Comment by jsoref** [comment]
Err, accidental damage. I was just trying to delete all the random branches in my repo that weren't mine -- missed that this one was mine.

**Comment by bitwiseman** [comment]
Cool, once it builds again, I'll merge.  We're well past 2.190.1 as the LTS.

**Comment by bitwiseman** [comment]
We should merge this before #410

**Review by bitwiseman — APPROVED** [review]

**Comment by bitwiseman** [comment]
@jsoref Long wait, but thanks for this one!

**Pull request merged**
