### PR TITLE
Log feedback for skipped stages

### PR DESCRIPTION
**Pull request by abayer**
It's a bit confusing when you see the stage step in the logs for a
skipped stage but no steps executed. There should be log messages for
the skip cases. So, well, here they are.

cc @reviewbybees esp @batmat @rsandell

### CODE REVIEW

**Comment by batmat** [comment]
:bee: \o/ Merci !

**Comment by rsandell** [comment]
But now you actually have steps in the stage ;)

**Comment by batmat** [comment]
@rsandell for stage view right now, it's better since it will show an empty stage, but maybe this would cause issues to BO? Andrew says BO shows those stages disabled in a clearer way, but how does it identify those? 

cc @michaelneale @i386 ?

**Comment by abayer** [comment]
@rsandell Yeah, that's a good point, actually - @vivek, will this cause problems in Blue Ocean visualization if skipped stages have the one `echo` invocation? I know there were problems when we had an `echo` at the end of a failed stage, but can't remember if that would be an issue here.

**Comment by vivek** [comment]
@abayer Blueocean shows skipped stage as not built, if you have a step inside it, its going to show up thats kind of odd. cc: @i386, @michaelneale

**Comment by rsandell** [comment]
If you could somehow get a hold of the active TaskListener and just do `getLogger().println(...)` I guess it wouldn't show up as a step invocation.

**Comment by abayer** [comment]
@rsandell @vivek Got a `TaskListener` approach up now. =)

**Comment by vivek** [comment]
@abayer thats better, thanks:)

**Pull request merged**
