### PR TITLE
[JENKINS-47703] - allow building dockerfile on Windows

### PR DESCRIPTION
**Pull request by casz**
* JENKINS issue(s):
    * [JENKINS-47703](https://issues.jenkins-ci.org/browse/JENKINS-47703)
* Description:
    * Support docker image build on Windows, related to https://github.com/jenkinsci/docker-workflow-plugin/pull/184
* Documentation changes:
    * N/A
* Users/aliases to notify:
    * @bitwiseman

### CODE REVIEW

**Comment by casz** [comment]
Would be great to include in current release and the beta

**Comment by casz** [comment]
:pray:

**Comment by casz** [comment]
Poking @dwnusbaum and @bitwiseman 😓

**Comment by henryborchers** [comment]
I'm hoping this can go through soon. Access to building Dockerfiles on Windows will allow me to actually use the Windows Docker containers in Jenkins. It'll drastically allow me to simplify my pipelines and make them scale.

**Comment by gegles** [comment]
Any update? Can this go through?

**Comment by casz** [comment]
@dwnusbaum @bitwiseman @oleg-nenashev should I go ahead and ask for commit access and release permission?

**Comment by gegles** [comment]
@dwnusbaum @bitwiseman @oleg-nenashev any chance you could unblock this? Much appreciated.

**Comment by henryborchers** [comment]
@bitwiseman, do you have any plans on reviewing this?

**Comment by oleg-nenashev** [comment]
@casz @gegles I do not maintain this repo, but I will pass your ping to @bitwiseman and @dwnusbaum in my company's internal slack

**Comment by bitwiseman** [comment]
Pardon me, I've been head down on #355.

**Comment by bitwiseman** [comment]
@casz Once again sorry for the delay.  This look reasonable. From what I can see the Docker tests are not running (on linux or windows) in CI due to infra issues.

I assume you've tested this manually locally?

**Comment by casz** [comment]
Before
```
13:11:15  [Pipeline] Start of Pipeline
13:11:16  [Pipeline] node
13:11:16  Running on windows_docker-3 in C:/jenkins/workspace/repo_master
13:11:16  [Pipeline] {
13:11:16  [Pipeline] stage
13:11:16  [Pipeline] { (Declarative: Checkout SCM)
13:11:16  [Pipeline] checkout
13:11:19  using credential gitlab_ssh_key
13:11:19  Cloning the remote Git repository
13:11:19  Cloning repository git@git.company.com:Shared/repo.git
13:11:19   > git init C:\jenkins\workspace\repo_master # timeout=10
13:11:19  Fetching upstream changes from git@git.company.com:Shared/repo.git
13:11:19   > git --version # timeout=10
13:11:19  using GIT_SSH to set credentials SSH key for GitLab
13:11:19   > git fetch --tags --force --progress -- git@git.company.com:Shared/repo.git +refs/heads/*:refs/remotes/origin/* # timeout=10
13:11:20   > git config remote.origin.url git@git.company.com:Shared/repo.git # timeout=10
13:11:20  Checking out Revision 6977f45ac6693496890b16e8e8912d1789ae8368 (master)
13:11:20  Enabling Git LFS pull
13:11:20   > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
13:11:20   > git config remote.origin.url git@git.company.com:Shared/repo.git # timeout=10
13:11:20  Fetching upstream changes from git@git.company.com:Shared/repo.git
13:11:20  using GIT_SSH to set credentials SSH key for GitLab
13:11:20   > git fetch --tags --force --progress -- git@git.company.com:Shared/repo.git +refs/heads/master:refs/remotes/origin/master # timeout=10
13:11:20   > git config core.sparsecheckout # timeout=10
13:11:20   > git checkout -f 6977f45ac6693496890b16e8e8912d1789ae8368
13:11:20   > git config --get remote.origin.url # timeout=10
13:11:20  using GIT_SSH to set credentials SSH key for GitLab
13:11:20   > git lfs pull origin
13:11:21  Commit message: "indents 😰"
13:11:21   > git rev-list --no-walk 4f1da9f28a4eae8c890f59061b5f6961fe2b253e # timeout=10
13:11:22  [GitLab Pipeline Status] Notifying branch build status: RUNNING Shared/repo/master: Build started...
13:11:22  [Pipeline] }
13:11:22  [Pipeline] // stage
13:11:22  [Pipeline] withEnv
13:11:22  [Pipeline] {
13:11:22  [Pipeline] stage
13:11:22  [Pipeline] { (Declarative: Agent Setup)
13:11:23  [Pipeline] isUnix
13:11:23  [Pipeline] readFile
13:11:23  [Pipeline] sh
13:11:23  + docker build -t 6ea565d2baf6a34cf59ae7821dd7571dba6e3e92 -f Dockerfile.CLI .
```

after
```
05:28:31  Running on windows in c:/jenkins/workspace/update
05:28:31  [Pipeline] {
05:28:31  [Pipeline] stage
05:28:31  [Pipeline] { (Declarative: Checkout SCM)
05:28:32  [Pipeline] checkout
05:28:37  using credential gitlab_ssh_key
05:28:37  Cloning the remote Git repository
05:28:37  Cloning repository git@git.company.com:Group/repo.git
05:28:37   > git init c:\jenkins\workspace\update # timeout=10
05:28:37  Fetching upstream changes from git@git.company.com:Group/repo.git
05:28:37   > git --version # timeout=10
05:28:37  using GIT_SSH to set credentials SSH key for GitLab
05:28:38   > git fetch --tags --force --progress -- git@git.company.com:Group/repo.git +refs/heads/*:refs/remotes/origin/*
05:28:39   > git config remote.origin.url git@git.company.com:Group/repo.git # timeout=10
05:28:39   > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
05:28:39   > git config remote.origin.url git@git.company.com:Group/repo.git # timeout=10
05:28:39  Fetching upstream changes from git@git.company.com:Group/repo.git
05:28:39  using GIT_SSH to set credentials SSH key for GitLab
05:28:39   > git fetch --tags --force --progress -- git@git.company.com:Group/repo.git +refs/heads/*:refs/remotes/origin/*
05:28:40  Checking out Revision 6977f45ac6693496890b16e8e8912d1789ae8368 (refs/remotes/origin/master)
05:28:40   > git rev-parse "refs/remotes/origin/master^{commit}" # timeout=10
05:28:40   > git rev-parse "refs/remotes/origin/origin/master^{commit}" # timeout=10
05:28:40   > git config core.sparsecheckout # timeout=10
05:28:40   > git checkout -f 6977f45ac6693496890b16e8e8912d1789ae8368
05:28:41  Commit message: "indents 😰"
05:28:41  First time build. Skipping changelog.
05:28:41  [Pipeline] }
05:28:41  [Pipeline] // stage
05:28:41  [Pipeline] withEnv
05:28:41  [Pipeline] {
05:28:41  [Pipeline] stage
05:28:41  [Pipeline] { (Declarative: Agent Setup)
05:28:41  [Pipeline] isUnix
05:28:41  [Pipeline] readFile
05:28:42  [Pipeline] bat
05:28:42  
05:28:42  c:\jenkins\workspace\update>docker build -t f90d1c0c99f7b6b52bdfb6cc8a501fdead79833d -f "Dockerfile.CLI" "." 
```

**Comment by casz** [comment]
@bitwiseman I demonstrated your assumption so what are the chances for getting a merge/release? 🤔

**Comment by bitwiseman** [comment]
@casz 
How about 1.4.0?  Doing it now.

**Comment by casz** [comment]
That works too @bitwiseman 🥰

**Pull request merged**
