### PR TITLE
Deleting `ToolsTest.buildPluginParentPOM`

### PR DESCRIPTION
**Pull request by jglick**
A bad test broken by https://github.com/jenkinsci/plugin-pom/pull/419. Noticed in https://github.com/jenkinsci/bom/pull/580 though that update did not _cause_ the failure.

### CODE REVIEW

**Review by basil — APPROVED** [review]
> Noticed in [jenkinsci/bom#580](https://github.com/jenkinsci/bom/pull/580)

Noticed in jenkinsci/bom#582 as well.

**Comment by jglick** [comment]
Right, it is just broken in all branches.

**Review by bitwiseman — APPROVED** [review]

**Comment by jglick** [comment]
Reminder that this needs a release (and maybe even backports).

**Comment by jglick** [comment]
ping @bitwiseman @car-roll etc.

**Pull request merged**
