### PR TITLE
Stabilize Windows build

### PR DESCRIPTION
**Pull request by basil**
The Windows build appears to have become destabilized recently. This PR attempts to stabilize the build by skipping the failing tests on Windows.

### CODE REVIEW

**Comment by basil** [comment]
CC @car-roll

**Comment by basil** [comment]
The incremental build from this PR has been successfully tested with Java 17 in the draft PR jenkinsci/bom#935. In order to help facilitate the transition of that draft PR into non-draft status, it would be helpful for this PR to be merged and released.

**Comment by car-roll** [comment]
Looks like #498 was merged a bit prematurely. But what kind of dependency update would have caused these git `filename` too long errors?

**Comment by basil** [comment]
Not sure offhand.

**Comment by basil** [comment]
> But what kind of dependency update would have caused these git filename too long errors?

@car-roll So rather than answering this question, you reverted the whole PR, setting back my Java 17 efforts?

**Comment by car-roll** [comment]
@basil No, the problem was that #498 should  never have been merged without those issues being resolved in the first place. I went ahead and refiled #502 so we can continue to diagnose the problem. My  concern was that then any additional PRs that would have been merged to declarative that were considered "significant" would then trigger a release via automated CD and then would have caused downstream failures in PCT.

**Comment by basil** [comment]
Closing in favor of #503.

**Pull request closed without merging**
