### PR TITLE
[FIXED JENKINS-37928] Properly detect sections without values.

### PR DESCRIPTION
**Pull request by abayer**
[JENKINS-37928](https://issues.jenkins-ci.org/browse/JENKINS-37928)

The exact error message could be better - I need to understand what
other possible ways this could fail to be a method call expression
besides just not having arguments, but this should be general enough a
message for all possibilities for now.

cc @reviewbybees esp @oleg-nenashev @batmat @svanoort @michaelneale

### CODE REVIEW

**Comment by abayer** [comment]
ping @reviewbybees ?

**Comment by michaelneale** [comment]
Looks ok - although it may confuse people by calling "agent" a section (at least the wording) - vs suggesting what comes after it? 
Given that :bee:

**Comment by abayer** [comment]
"section" is any of the top-level elements. I have no better word for them. =)

**Comment by michaelneale** [comment]
no "section" is fine, I am just spitballing: 

"Not a valid section definition: 'agent'"

specifically for agent it would read like: 

"Not a valid section definition: 'agent'. You are missing configuration options like: label:'master'"

Perhaps there is a more generic way to express they should look up the docs on what to put after the section? (it isn't just agent...)

that is all I mean

**Comment by abayer** [comment]
Feel free to open a ticket for the contextual messages - getting that kind of suggestion logic will take some work.

**Comment by michaelneale** [comment]
"Not a valid section definition: 'agent'. Some extra configuration is required"

would that work?

**Comment by abayer** [comment]
Works for me. Changing now.

**Pull request merged**
