### PR TITLE
JENKINS-38152 - expose execution model on WorkflowRun

### PR DESCRIPTION
**Pull request by abayer**
[JENKINS-38152](https://issues.jenkins-ci.org/browse/JENKINS-38152)

Very much a work-in-progress at this point, but thought I'd get this up for initial feedback.

cc @reviewbybees esp @vivek

### CODE REVIEW

**Comment by svanoort** [comment]
Hmm.  This is basically like getting source to execution direct mapping options?  I like that.

**Comment by abayer** [comment]
Ok, this isn't actually a work-in-progress now, I think. Test added, it works, I properly strip out source locations...wait, I should test that too.

**Comment by abayer** [comment]
Source location stripping tests added. Oh, and cc @i386, 'cos you may be interested.

**Comment by abayer** [comment]
@svanoort Yeah, not sure if I should be exposing the *entire* model or just the stages - the discussion this came out of was just talking about stages, but we may want to shift to exposing the whole model. Blue Ocean wants this. =)

**Comment by abayer** [comment]
fwiw, I'd still ideally like to stash the `ModelASTPipelineDef` that's actually generated at `Jenkinsfile`-compilation time and reuse that, rather than re-parsing/re-compiling it at execution time, but...so far, I can't figure out how to do that. But I bet I will eventually. =)

**Comment by i386** [comment]
😍😍😍

**Comment by abayer** [comment]
Most recent commit also added `EXTENDING.md` with reference material for REST API endpoints and Java API stuff.

**Pull request merged**
