### PR TITLE
[JENKINS-41185] Initial work on when and/not/or

### PR DESCRIPTION
**Pull request by abayer**
[JENKINS-41185](https://issues.jenkins-ci.org/browse/JENKINS-41185)

Post-1.0 feature, this is just the first work. Still needs negative
testing to make sure it doesn't, y'know, fail horribly when there are
problems, but I'll pick this back up again post-1.0.

### CODE REVIEW

**Comment by rsandell** [comment]
On a quick glance it looks to be an api breaking change in pipeline-model-api and we are not supposed to have those post 1.0

**Comment by abayer** [comment]
@rsandell That's an interesting point. The guarantee we've made is syntax compatibility, not backend API compatibility - this change wouldn't break either `Jenkinsfile` syntax or JSON representation. I'll do a check to make sure nothing out there is depending on `pipeline-model-api`'s API, but I'm fairly sure there isn't at this point, so we should still be ok.

**Comment by rsandell** [comment]
Well API compatibility is imho just a default strive in the Jenkins project and any deviation from that needs to have motivation. especially on a module whose sole purpose is to be an API :)

**Comment by abayer** [comment]
Replacing with a new PR.

**Pull request closed without merging**
