### PR TITLE
[FIXED JENKINS-37932] Add "agent any"

### PR DESCRIPTION
**Pull request by abayer**
[JENKINS-37932](https://issues.jenkins-ci.org/browse/JENKINS-37932)

Better approach for "run anywhere". I think this gets rid of any need
to make the agent section optional, at least for now.

cc @reviewbybees esp @vivek @michaelneale @i386

### CODE REVIEW

**Comment by vivek** [comment]
LGTM 🐝 pending CI run.

**Comment by vivek** [comment]
@abayer I am assuming its going to be backward compatible with scripts with agent: ""?

**Comment by abayer** [comment]
@vivek Yup, `agent label:""` still works fine. I just added a new tweak. =)

**Comment by HRMPW** [comment]
:bee:

**Comment by i386** [comment]
Delicious sugar 🍭

**Comment by i386** [comment]
@abayer can you please update the docs on my Jenkins.io fork and the wiki?

**Comment by abayer** [comment]
Once it's released, yes.

**Pull request merged**
