### PR TITLE
[FIXED JENKINS-38426] Require non-literal env vars to be single-quoted.

### PR DESCRIPTION
**Pull request by abayer**
[JENKINS-38426](https://issues.jenkins-ci.org/browse/JENKINS-38426)

This way, we can delay evaluation until runtime in the right context
and get the right values without any security exception etc.

This may not be ideal - but as of right now, it's the best approach
I've got.

cc @reviewbybees esp @vivek @rsandell @HRMPW @michaelneale @i386

### CODE REVIEW

**Comment by michaelneale** [comment]
I was hoping I could do this: 

```
pipeline {
    agent label:''
    
    stages {
        stage('build') {
            sh 'echo $YEAH'
        }
        
    }
    
    environment {
        YEAH = '${thing()}'
    }
    
}

def thing() {
    return "HEY"
}
```

But can't. 

Also: 

```
pipeline {
    agent label:''
    
    stages {
        stage('build') {
            sh 'echo $YEAH'
        }
        
    }
    
    environment {
        YEAH = thing()
    }
    
}

def thing() {
    return "HEY"
}
```

fails - should that be possible?

**Comment by abayer** [comment]
The latter I'm not prepared for yet. =)

The former...hmm. Gotta think about how to do that. It'll work fine for a lot of things, but not for that use case right now.

Again, both will be much easier if we moved to 
```groovy
environment {
    foo bar()
}
```

**Comment by HRMPW** [comment]
Would syntax without "=" work for all permutations?

`environment {
     foo bar() 
     HEY "Yah"
     BIG 'Bang'
}`

**Comment by abayer** [comment]
@HRMPW As I mentioned on the JIRA, there may be issues with variable names in all caps - I remember hitting problems with that in the past. I'd have to play with it to be sure.

**Comment by michaelneale** [comment]
@abayer I just want to test it with globals etc - so I just need to a spare day to find out how they work now.

**Comment by HRMPW** [comment]
This might be a stupid question but for the environment block is it possible for the delegate to take each line as a string so you can manipulate any way you want and then _evaluate_ the string after manipulation?

**Comment by abayer** [comment]
Sadly, no. Variable assignment as an operation messes things up.

**Comment by michaelneale** [comment]
@abayer I wasn't able to make global libs work (not for this PR, but everything as described: https://github.com/jenkinsci/workflow-cps-global-lib-plugin doesn't actually seem to work) - so I don't know how to validate this.

**Comment by michaelneale** [comment]
ok, finally was able to make it work (upgrading and multiple restarting). 

So I think this might be ok. 

The single quote may be confusing (but we are using single quotes most every where else) to a pipeline "expert". 

Also calling a function like 

```
AWS_KEY_ID = '${secret("thing")}'
```

instead of 
```
AWS_KEY_ID = secret("thing")
```

looks and is hard to explain. So many quotes to understand, no one will get it right. So I am not sure. I think this is an ok starting point, if it didn't block the way off in the future for direct functions that aren't in a string?

**Comment by abayer** [comment]
So after further experimentation...

- `FOO "BAR"` syntax doesn't work because Groovy doesn't accept `FOO` as a method name. `"FOO" "BAR"` does work, though.
- neither `"FOO" currentBuild.getNumber()` nor `FOO = currentBuild.getNumber()` can work. In both cases, the `currentBuild.getNumber()` gets evaluated too early. Basically, any non-literal, non-closure expression has to be within a closure that we're not evaluating at parse-time or that expression gets evaluated at parse-time rather than execution-time.

So the problem isn't actually the variable assignment - I was wrong about that. I'll try to see if there are any alternatives.

**Comment by abayer** [comment]
Closing in favor of #22

**Pull request closed without merging**
