### PR TITLE
Use joda-time api plugin

### PR DESCRIPTION
**Pull request by jonesbusy**
Use joda-time-api plugin

- [x] Remove version when bom released https://github.com/jenkinsci/bom/pull/2732

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by jonesbusy** [comment]
Fixed conflicts

**Review by NotMyFault — APPROVED** [review]
Thanks!

**Review by olamy — APPROVED** [review]

**Comment by balakine** [comment]
I understand why it's excluded, but why do we need this dependency? I don't see a single import of org.joda.

**Comment by basil** [comment]
> I understand why it's excluded, but why do we need this dependency? I don't see a single import of org.joda.

We consume it transitively via `json-schema-validator`.

**Pull request merged**
