### PR TITLE
Run empty stages for conditionally-skipped stages.

### PR DESCRIPTION
**Pull request by abayer**
This is just a band-aid until JENKINS-38153 lands with a better
solution involving tags metadata and all that jazz, but this'll at
least make sure our execution plan matches reality for now.

cc @reviewbybees esp @rsandell @HRMPW @i386

### CODE REVIEW

**Comment by i386** [comment]
so this goes and creates a flow node for a conditional stage even if it doesn't really get run?

**Comment by abayer** [comment]
Yes, same as we've long been doing for stages after a failed stage.

**Comment by i386** [comment]
Sounds good to me 💯

**Comment by rsandell** [comment]
Well by principal I don't like it. ;)

**Comment by abayer** [comment]
@rsandell =P

**Pull request merged**
