### PR TITLE
Allow stage-only DeclarativeOptions

### PR DESCRIPTION
**Pull request by abayer**
* JENKINS issue(s):
    * n/a
* Description:
    * No concrete use case for this right now, but I've got some possibilities I'm brewing that would want this elsewhere, so let's get it in so that it'll be available in 1.2.8.
* Documentation changes:
    * n/a
* Users/aliases to notify:
    * ...

### CODE REVIEW

**Comment by abayer** [comment]
@rsandell fwiw, https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/256/files/51f25e2d69d9662dcdd8b9792739c337b03ef67c..e60068f48aa6dbb42189696620d613ff3791da45 is the relevant changes here.

**Comment by rsandell** [comment]
@abayer yepp, that part I think looks good, but this can't be merged until the snippetizer is approved and merged, so I can't really approve this either :)

**Comment by abayer** [comment]
Fair enough!

**Comment by abayer** [comment]
That's a good point - will revisit.

**Pull request merged**
