### PR TITLE
Refactoring tests to use the expect(...) tooling.

### PR DESCRIPTION
**Pull request by abayer**
Bobby wrote this nice stuff a few weeks ago and we should really be
using it everywhere here, so, let's use it everywhere here. There are
still a couple weird cases where I couldn't figure out an easy way to
translate the tests into the expect(...) approach, but 95% or so of
the run-from-repo tests are now expect(...)-style.

cc @reviewbybees esp @rsandell

### CODE REVIEW

**Comment by rsandell** [comment]
looks good except for the archived files check that I have a more elaborate implementation of in #46

**Comment by abayer** [comment]
@rsandell Yup, updated to use that.

**Comment by rsandell** [comment]
:bee:

**Comment by rsandell** [comment]
:bee:

**Pull request merged**
